language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3.3-5.5-alpha"
sudo: false
script:
  - "nosetests"
after_success:
  - codecov
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a3003f118577918a4392
